services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: researchflow-postgres

    environment:
      POSTGRES_DB: researchflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - researchflow_pgdata:/var/lib/postgresql/data

volumes:
  researchflow_pgdata: