spring.application.name=research-assistant
gemini.api.url = https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=
gemini.api.key = ${GEMINI_KEY}

spring.ai.google.genai.api-key=${GEMINI_KEY}
spring.ai.google.genai.embedding.api-key=${GEMINI_KEY}
spring.ai.google.genai.embedding.text.model=text-embedding-004

spring.datasource.url=jdbc:postgresql://localhost:5433/researchflow
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
